// export const EmployeeCurrentData = [
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
// ];
// export const EmployeePreviousData = [
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
//   {
//     managerName: "ABC",
//     managerID: "#123456",
//     projectName: "CBA",
//     projectID: "#123456",
//     hours: "45",
//     stat: "InDraft",
//   },
// ];

export const EmployeeCurrentData = {
  header: [
    "TimeSheet ID",
    "Manager Name",
    "Total Hours",
    "Start date",
    "End date",
    "Status",
  ],
  body: [
    {
      id: "#OD1713",
      user: "anthony baker",
      startDate: "27 Jun 2021",
      endDate: "27 Jun 2021",
      hours: "15",
      status: "Pending",
    },
    {
      id: "#OD1712",
      user: "frank iva",
      startDate: "1 Jun 2021",
      endDate: "1 Jun 2021",
      hours: "12",
      status: "Pending",
    },
    {
      id: "#OD1713",
      user: "anthony baker",
      startDate: "27 Jun 2021",
      endDate: "27 Jun 2021",
      hours: "30",
      status: "Cancelled",
    },
    {
      id: "#OD1711",
      user: "john doe",
      startDate: "17 Jun 2021",
      endDate: "17 Jun 2021",
      hours: "20",
      status: "Approved",
    },
    {
      id: "#OD1712",
      user: "frank iva",
      startDate: "1 Jun 2021",
      endDate: "1 Jun 2021",
      hours: "8",
      status: "Cancelled",
    },
  ],
};
